main:
	rm fullSeason.xlsx
	python3 main.py
	code fullSeason.xlsx

fantasy:
	rm fullfantasySeason.xlsx
	python3 fantasyCalc.py
	code fullfantasySeason.xlsx

game:
	rm today.xlsx
	rm yesterday.xlsx
	python3 gamedata.py
	code today.xlsx
	code yesterday.xlsx